import test from 'node:test';
import assert from 'node:assert/strict';
import { revision, steps, inventory, validate, throughStep, size, toCsv, dimensions, type Placement } from '../lib/assembly.ts';
test('sample has unique, nonoverlapping, fully supported placements', () => { const result = validate(revision.placements); assert.equal(result.placements, 49); assert.equal(result.cells, 744); assert.deepEqual(result.errors, []); });
test('inventory and CSV derive from the same selected revision', () => { const lots = inventory(revision.placements); assert.equal(lots.reduce((sum, l) => sum + l.quantity, 0), 49); assert.equal(inventory(revision.placements.slice(1)).reduce((sum, l) => sum + l.quantity, 0), 48); const csv = toCsv(revision.placements).split('\r\n'); assert.equal(csv.length, lots.length + 1); assert.equal(csv.slice(1).reduce((sum, row) => sum + Number(row.split(',').at(-1)), 0), 49); assert.ok(csv.slice(1).every(row => row.startsWith(revision.id + ',Unvalidated sample,'))); });
test('instructions introduce each placement exactly once and reconstruct the full sample', () => { const introduced = steps.flatMap(s => s.placements.map(p => p.id)); assert.equal(new Set(introduced).size, 49); assert.deepEqual(introduced.toSorted(), revision.placements.map(p => p.id).toSorted()); assert.deepEqual(throughStep(steps.length - 1), revision.placements); for (let i = 0; i < steps.length; i++) {
    assert.deepEqual(validate(throughStep(i), { requireConnected: false }).errors, []);
    if (i)
        assert.ok(steps[i].y > steps[i - 1].y);
} });
test('rotations and dimensions respect stud and plate units', () => { const p = revision.placements.find(p => p.rotation === 90)!; assert.deepEqual(size(p), { x: 4, y: 3, z: 2 }); assert.deepEqual(dimensions(revision.placements), { width: 8, depth: 6, height: 20 }); });
test('invalid and collision fixtures fail checks', () => { const duplicate = { ...revision.placements[0], id: 'collision' }; assert.ok(validate([...revision.placements, duplicate]).errors.some(e => e.startsWith('Collision'))); assert.ok(validate([{ ...revision.placements[0], y: 50 }]).errors.some(e => e.startsWith('Unsupported'))); assert.ok(validate([{ ...revision.placements[0], x: 0.5 }]).errors.some(e => e.startsWith('Invalid'))); assert.ok(validate([{ ...revision.placements[0], part: 'unknown' } as unknown as Placement]).errors.some(e => e.startsWith('Invalid'))); });
test('vertical connections form one component; disconnected and empty assemblies fail', () => { assert.equal(validate(revision.placements).components, 1); assert.ok(validate([]).errors.includes('Empty assembly')); const a = revision.placements[0]; assert.ok(validate([a, { ...a, id: 'separate', x: 20 }]).errors.some(e => e.startsWith('Disconnected'))); });
