import test from 'node:test';
import assert from 'node:assert/strict';
import {importLDraw} from '../lib/ldraw/import.ts';
import {compose,identity,parseUpload,importedInventory} from '../lib/ldraw/model.ts';
import {officialCandidates} from '../lib/ldraw/library-path.ts';
const colors='0 !COLOUR Red CODE 4 VALUE #C91A09 EDGE #333333\n0 !COLOUR Yellow CODE 14 VALUE #F2CD37 EDGE #333333';
const part='0 Brick fixture\n0 !LDRAW_ORG Part\n3 16 0 0 0 20 0 0 0 20 0';
const ref=(color=4,name='brick.dat',x=0)=>`1 ${color} ${x} 0 0 1 0 0 0 1 0 0 0 1 ${name}`;
const fetchPart=async(name:string)=>({path:'parts/'+name,text:part});
const run=(text:string,fetcher=fetchPart)=>importLDraw('test.ldr',text,colors,fetcher,new AbortController().signal);
test('authored steps, final cumulative quantities and duplicates match',async()=>{const model=await run([ref(),ref(),'0 ROTSTEP 0 90 0 REL',ref(14)].join('\n'));assert.equal(model.placements.length,3);assert.deepEqual(model.steps.map(s=>s.placementIds.length),[2,1]);assert.equal(importedInventory(model.placements)[0].quantity,2);assert.ok(model.warnings.some(w=>w.includes('ROTSTEP')));assert.equal(model.dependencyCount,1);});
test('no authored steps never manufactures instructions',async()=>{const m=await run(ref());assert.equal(m.hasSteps,false);assert.deepEqual(m.steps,[]);assert.equal(m.placements.length,1);});
test('MPD submodel composition and parent step membership',async()=>{const m=await run(['0 FILE main.ldr',ref(4,'sub.ldr',10),'0 STEP',ref(14,'sub.ldr',50),'0 FILE sub.ldr',ref(16,'brick.dat',5),'0 STEP',ref(16,'brick.dat',15)].join('\n'));assert.deepEqual(m.placements.map(p=>[p.transform[0],p.color,p.step]),[[15,'4',0],[25,'4',0],[55,'14',1],[65,'14',1]]);assert.ok(m.warnings.some(w=>w.includes('Submodels')));});
test('affine composition preserves rotation and translation',()=>{const parent=[10,20,30,0,-1,0,1,0,0,0,0,1];assert.deepEqual(compose(parent,[5,0,0,...identity.slice(3)]).slice(0,3),[10,25,30]);});
test('reject traversal, malformed matrices, duplicate blocks and missing submodels',async()=>{assert.throws(()=>parseUpload('x.ldr',ref(4,'../secret.dat')),/reference/);assert.throws(()=>parseUpload('x.ldr','1 4 0 0 0 0 0 0 0 0 0 0 0 0 brick.dat'),/singular/);assert.throws(()=>parseUpload('x.mpd','0 FILE A.ldr\n'+ref()+'\n0 FILE a.ldr'),/Duplicate/);await assert.rejects(run(ref(4,'missing.ldr')),/Missing submodel/);});
test('dependency errors and cycles fail the entire import',async()=>{await assert.rejects(run(ref(),async()=>{throw Error('Missing brick.dat');}),/Missing/);await assert.rejects(run(ref(),async name=>({path:'parts/'+name,text:part+'\n'+ref(16)})),/Cyclic/);});
test('embedded part resolves without requests and keeps custom provenance',async()=>{const m=await run('0 FILE main.ldr\n'+ref()+'\n0 STEP\n0 FILE brick.dat\n'+part,async()=>{throw Error('Unexpected fetch');});assert.equal(m.placements[0].origin,'embedded');assert.equal(m.librarySources.length,0);});
test('fixed library paths reject URL and traversal input',()=>{assert.deepEqual(officialCandidates('3001.dat'),['parts/3001.dat','p/3001.dat']);assert.deepEqual(officialCandidates('s\\3001s01.dat'),['parts/s/3001s01.dat']);for(const p of ['https://x/a.dat','../a.dat','parts/../../a.dat','/a.dat','a.ldr'])assert.throws(()=>officialCandidates(p));});
test('cancel and unknown colors fail explicitly',async()=>{const c=new AbortController();c.abort();await assert.rejects(importLDraw('a.ldr',ref(),colors,fetchPart,c.signal));await assert.rejects(run(ref(999999)),/Unknown color/);});
