import test from 'node:test';
import assert from 'node:assert/strict';
import {servePart,type PublicPartCache} from '../lib/ldraw/part-service.ts';
import {createPartTransport,retryDelay,abortableWait} from '../lib/ldraw/transport.ts';
const text='0 Public fixture\n3 16 0 0 0 1 0 0 0 1 0';
const signal=()=>new AbortController().signal;
function memoryCache():PublicPartCache{const map=new Map<string,Response>();return {async match(k){return map.get(k.url)?.clone();},async put(k,r){map.set(k.url,r.clone());}};}
test('canonical edge cache includes successful primitive fallback, skips vendor on repeat',async()=>{let calls=0;const cache=memoryCache();const fetcher=(async(input:RequestInfo|URL,init?:RequestInit)=>{calls++;assert.equal(init?.redirect,'manual');return String(input).includes('/parts/')?new Response(null,{status:404}):new Response(text);}) as typeof fetch;const req=new Request('https://site.test/api/ldraw-part?file=stud.dat');const first=await servePart(req,fetcher,cache);assert.equal((await first.json() as {path:string}).path,'p/stud.dat');assert.equal(calls,2);const second=await servePart(req,fetcher,cache);assert.equal(second.headers.get('X-LDraw-Cache'),'HIT');assert.equal(calls,2);});
test('rate limit status and retry-after survive without being cached',async()=>{let puts=0;const cache={async match(){return undefined;},async put(){puts++;}};const response=await servePart(new Request('https://site.test/api/ldraw-part?file=3001.dat'),(async()=>new Response(null,{status:429,headers:{'Retry-After':'17'}})) as typeof fetch,cache);assert.equal(response.status,429);assert.equal(response.headers.get('Retry-After'),'17');assert.equal(puts,0);});
test('cache failure is nonfatal and invalid paths never fetch',async()=>{const cache={async match(){throw Error('Cache unavailable');},async put(){throw Error('Cache unavailable');}};let calls=0;const f=(async()=>{calls++;return new Response(text);}) as typeof fetch;assert.equal((await servePart(new Request('https://site.test/api/ldraw-part?file=3001.dat'),f,cache)).status,200);assert.equal((await servePart(new Request('https://site.test/api/ldraw-part?file=../secret.dat'),f,cache)).status,400);assert.equal(calls,1);});
test('paced browser retry honors rate limit and retains public cache',async()=>{let calls=0,clock=0;const waits:number[]=[];const transport=createPartTransport({now:()=>clock,wait:async(ms,s)=>{s.throwIfAborted();waits.push(ms);clock+=ms;},fetch:(async()=>{calls++;return calls===1?new Response(null,{status:429,headers:{'Retry-After':'3'}}):Response.json({path:'parts/3001.dat',text});}) as typeof fetch});await transport('3001.dat',signal());assert.ok(waits.includes(3000));await transport('3001.dat',signal());assert.equal(calls,2);});
test('404 does not retry and failed responses do not enter browser cache',async()=>{let calls=0;const transport=createPartTransport({wait:async()=>{},fetch:(async()=>{calls++;return Response.json({error:'Missing'},{status:404});}) as typeof fetch});await assert.rejects(transport('3001.dat',signal()),/Missing/);await assert.rejects(transport('3001.dat',signal()),/Missing/);assert.equal(calls,2);});
test('cancellation interrupts retry delay without another request',async()=>{const c=new AbortController();let calls=0;const transport=createPartTransport({fetch:(async()=>{calls++;return new Response(null,{status:429,headers:{'Retry-After':'60'}});}) as typeof fetch});const result=transport('3001.dat',c.signal,()=>c.abort(Error('Cancelled')));await assert.rejects(result,/Cancelled/);assert.equal(calls,1);const aborted=new AbortController();aborted.abort();await assert.rejects(async()=>abortableWait(1000,aborted.signal));});
test('retry-after supports HTTP dates and does not shorten server delays',()=>{assert.equal(retryDelay('120',0),120000);assert.equal(retryDelay('Thu, 01 Jan 1970 00:01:00 GMT',0),60000);assert.equal(retryDelay('nonsense',0),60000);});
test('cancelled incoming request never contacts upstream',async()=>{const c=new AbortController();c.abort();let calls=0;const result=await servePart(new Request('https://site.test/api/ldraw-part?file=3001.dat',{signal:c.signal}),(async()=>{calls++;return new Response(text);}) as typeof fetch);assert.equal(result.status,499);assert.equal(calls,0);});
test('in-flight upstream receives cancellation',async()=>{const c=new AbortController();let upstreamSignal:AbortSignal|undefined;const pending=servePart(new Request('https://site.test/api/ldraw-part?file=3001.dat',{signal:c.signal}),(async(_,init)=>{upstreamSignal=init!.signal!;c.abort();upstreamSignal.throwIfAborted();return new Response(text);}) as typeof fetch);assert.equal((await pending).status,499);assert.equal(upstreamSignal?.aborted,true);});
