'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,Box,Layers,BookOpen,ArrowLeft,ArrowRight,Download,FileCheck2,Info,FlaskConical} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {importLDraw} from '@/lib/ldraw/import';
import {importLimits,importedInventory,importedCsv} from '@/lib/ldraw/model';
import {prepareLDraw,disposeModel,type LoadedLDraw} from '@/lib/ldraw/render';
import {LDrawViewer} from './ldraw-viewer';
export function AdminTestBench({active=true}:{active?:boolean}){
 const [loaded,setLoaded]=useState<LoadedLDraw|null>(null);const current=useRef<LoadedLDraw|null>(null);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [missingSteps,setMissingSteps]=useState(false);const [tab,setTab]=useState('model');const [step,setStep]=useState(0);const [query,setQuery]=useState('');const input=useRef<HTMLInputElement>(null);const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>{request.current?.abort();if(current.current)disposeModel(current.current.group);},[]);
 async function upload(file:File){if(request.current)return;const control=new AbortController();request.current=control;const timer=setTimeout(()=>control.abort(new Error('Import timed out. Please retry with a smaller model.')),importLimits.timeoutMs);setBusy(true);setError('');setProgress('Reading your LDraw file…');let prepared:LoadedLDraw|null=null;
  try{if(file.size>importLimits.fileBytes)throw Error('Choose a file up to 5 MB.');const text=await file.text();control.signal.throwIfAborted();const colors=await fetch('/ldraw/LDConfig.ldr',{signal:control.signal});if(!colors.ok)throw Error('The color library could not be loaded. Please retry.');const revision=await importLDraw(file.name,text,await colors.text(),async(name,signal)=>{const response=await fetch('/api/ldraw-part?file='+encodeURIComponent(name),{signal});const data=await response.json().catch(()=>{throw Error('The part service returned an unexpected response. Please retry.');}) as {path:string;text:string;error?:string};if(!response.ok)throw Error(`${name}: ${data.error||'Could not load this part.'}`);return data;},control.signal,setProgress);await new Promise(resolve=>setTimeout(resolve,0));control.signal.throwIfAborted();prepared=await prepareLDraw(revision);control.signal.throwIfAborted();const old=current.current;current.current=prepared;setLoaded(prepared);prepared=null;setStep(0);setTab('model');setQuery('');setMissingSteps(!revision.hasSteps);if(old)disposeModel(old.group);
  }catch(cause){if(prepared)disposeModel(prepared.group);if(request.current===control)setError(cause instanceof Error?cause.message:'The file could not be imported.');}
  finally{clearTimeout(timer);if(request.current===control){request.current=null;setBusy(false);setProgress('');}}
 }
 function download(){if(!loaded)return;const url=URL.createObjectURL(new Blob([importedCsv(loaded.revision)],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=loaded.revision.fileName.replace(/\.(ldr|mpd)$/i,'')+'-parts.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const model=loaded?.revision;const lots=model?importedInventory(model.placements):[];const visible=model?.placements.filter(p=>p.step<=step)||[];const added=model?.placements.filter(p=>p.step===step)||[];
 return <section className="admin-bench"><header className="ldr-heading"><div><div className="eyebrow"><FlaskConical size={15}/> ADMIN TEST BENCH</div><h1>Test your LDraw model.</h1><p>Open an LDraw file and inspect its model, parts and authored assembly steps.</p></div><span className="ldr-local">Local session</span></header>
 <div className={"ldr-upload"+(model?" has-model":"")}><div className="ldr-upload-icon"><Upload size={27}/></div><div><h2>{model?'Test another model':'Start with your .ldr file'}</h2><p>.ldr or packed .mpd · Up to 5 MB · 2,500 placed parts</p><small>Your file stays in this browser. Referenced public part names are sent to the part library.</small></div><input ref={input} type="file" accept=".ldr,.mpd" className="sr-only" aria-label="Upload LDraw model" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void upload(file);}}/><button className="primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'Importing…':model?'Replace file':'Choose LDraw file'}</button></div>
 {busy&&<div className="ldr-status" role="status"><span className="ldr-spinner"/>{progress}<button onClick={()=>request.current?.abort(new Error('Import cancelled. Your previous model is still available.'))}>Cancel</button></div>}
 {error&&<div className="ldr-error" role="alert"><strong>Import could not finish</strong><p>{error}</p>{model&&<small>Your previous model is still available below.</small>}</div>}
 {!loaded?<div className="ldr-empty"><div className="ldr-empty-art"><Box size={72}/><span><Layers size={25}/></span></div><h2>A workbench for your own models.</h2><p>Rotate the real geometry, check each part and move through the assembly steps saved in your file.</p><a href="/ldraw/step-test.ldr" download>Download a small test file <Download size={16}/></a><div className="ldr-explainer"><span><Box size={20}/> Model inspection</span><span><Layers size={20}/> Parts inventory</span><span><BookOpen size={20}/> Authored steps</span></div></div>:<div className="ldr-result"><header className="ldr-model-heading"><div><span className="eyebrow"><FileCheck2 size={14}/> IMPORTED LDRAW</span><h2>{model!.fileName}</h2><p>{model!.placements.length.toLocaleString()} pieces · {lots.length} part / color combinations · {model!.hasSteps?`${model!.steps.length} authored steps`:'No assembly steps'}</p></div><span className="ldr-unvalidated">Buildability not verified</span></header>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="workbench-tabs"><TabsTrigger value="model"><Box size={17}/> Model</TabsTrigger><TabsTrigger value="parts"><Layers size={17}/> Parts</TabsTrigger><TabsTrigger value="instructions"><BookOpen size={17}/> Instructions</TabsTrigger></TabsList>
 <TabsContent value="model">{active&&<LDrawViewer loaded={loaded}/>}</TabsContent>
 <TabsContent value="parts"><div className="ldr-parts-toolbar"><input aria-label="Search imported parts" placeholder="Search parts or colors…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary" onClick={download}><Download size={16}/> Export CSV</button></div><Table><TableHeader><TableRow><TableHead>Part</TableHead><TableHead>Color</TableHead><TableHead>Quantity</TableHead></TableRow></TableHeader><TableBody>{lots.filter(l=>`${l.name} ${l.part} ${l.colorName} ${l.color}`.toLowerCase().includes(query.toLowerCase())).map(l=><TableRow key={l.key}><TableCell><strong>{l.name}</strong><small className="ldr-part-id">{l.part}{l.origin==='embedded'?' · Embedded custom part':''}</small></TableCell><TableCell><span className="ldr-color" style={{background:l.colorHex}}/>{l.colorName}</TableCell><TableCell>{l.quantity}</TableCell></TableRow>)}</TableBody></Table>{!lots.some(l=>`${l.name} ${l.part} ${l.colorName} ${l.color}`.toLowerCase().includes(query.toLowerCase()))&&<p className="ldr-no-results">No matching parts.</p>}</TabsContent>
 <TabsContent value="instructions">{model!.hasSteps?<><div className="ldr-stepbar"><div><span className="eyebrow">AUTHORED ASSEMBLY</span><h3>Step {step+1} of {model!.steps.length}</h3><p>{added.length} {added.length===1?'piece':'pieces'} added · {visible.length} of {model!.placements.length} placed</p></div><div className="ldr-step-controls"><Select value={String(step)} onValueChange={v=>setStep(Number(v))}><SelectTrigger aria-label="Choose imported assembly step"><SelectValue/></SelectTrigger><SelectContent>{model!.steps.map((s,i)=><SelectItem key={s.number} value={String(i)}>Step {s.number}</SelectItem>)}</SelectContent></Select><button className="secondary" aria-label="Previous imported step" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={17}/></button><button className="primary" disabled={step===model!.steps.length-1} onClick={()=>setStep(s=>s+1)}>Next step <ArrowRight size={17}/></button></div></div><div className="ldr-instructions">{active&&<LDrawViewer loaded={loaded} step={step}/>}<aside><h3>Pieces for this step</h3>{importedInventory(added).map(l=><div className="ldr-step-part" key={l.key}><span className="ldr-color" style={{background:l.colorHex}}/><div><strong>{l.name}</strong><small>{l.colorName} · {l.part}</small></div><b>×{l.quantity}</b></div>)}</aside></div></>:<div className="ldr-empty ldr-no-steps"><BookOpen size={38}/><h2>Assembly steps aren’t included</h2><p>This file has no STEP or ROTSTEP boundaries in its main model. Export it with assembly steps, then upload it again. You can still inspect the full model and its parts.</p><button className="primary" onClick={()=>setTab('model')}>View full model</button></div>}</TabsContent></Tabs>
 {model!.warnings.length>0&&<div className="ldr-notes"><strong><Info size={16}/> Import notes</strong><ul>{model!.warnings.map(w=><li key={w}>{w}</li>)}</ul></div>}<p className="ldr-provenance">Imported geometry and authored order are displayed as supplied. Connections, stability and physical buildability have not been verified.</p></div>}
 <footer className="ldr-attribution">Part geometry: <a href="https://library.ldraw.org/" target="_blank" rel="noreferrer">LDraw.org contributors</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Custom parts remain attributed to their file authors.</footer>
 <AlertDialog open={missingSteps} onOpenChange={setMissingSteps}><AlertDialogContent><AlertDialogTitle>Assembly steps aren’t included</AlertDialogTitle><AlertDialogDescription>This file has no STEP or ROTSTEP boundaries in its main model. Export it with assembly steps and upload it again to see the breakdown. The full model and parts are ready to inspect.</AlertDialogDescription><AlertDialogFooter><AlertDialogAction>View model</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
