"""Regenerate the public official geometry subset used by the hosted viewer."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
library = root / 'lego_builder/data/parts-library'
parts = {str(p.relative_to(library)): p.read_text() for p in sorted(library.rglob('*.dat'))}
destination = root / 'reconstruction-site/lib/ldraw/bundled-parts.ts'
destination.write_text('// Official LDraw subset from lego_builder/data/parts-library. Original license/author headers retained.\n// Generated by scripts/build_site_parts.py; geometry-only public data.\nexport const bundledParts: Record<string,string> = ' + json.dumps(parts,ensure_ascii=True,separators=(',',':')) + ';\n')
print(f'Bundled {len(parts)} official geometry files')
