import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
const root = new URL("../", import.meta.url);
const names = ["source-color-evidence.json", "source-color-expanded-evidence.json", "vehicle-color-evidence.json"];
const [legacy, expanded, vehicle] = names.map(name => JSON.parse(readFileSync(new URL(`lego_builder/data/${name}`, root), "utf8")));
function catalog(evidence, sourceName) {
  const codes = evidence.color_mappings.map(item => item.ldraw_color).sort((a,b) => a-b), parts = {};
  for (const item of [...evidence.lot_evidence, ...vehicle.lot_evidence]) {
    if (item.status !== "verified" || !codes.includes(item.ldraw_color)) continue;
    (parts[item.part_id] ??= new Set()).add(item.ldraw_color);
  }
  return { version: evidence.palette_version, codes, parts: Object.fromEntries(Object.entries(parts).sort(([a],[b]) => a.localeCompare(b)).map(([part, colors]) => [part, [...colors].sort((a,b) => a-b)])), evidenceSha256: [sourceName, "vehicle-color-evidence.json"].map(name => createHash("sha256").update(readFileSync(new URL(`lego_builder/data/${name}`, root))).digest("hex")) };
}
const catalogs = { [legacy.palette_version]: catalog(legacy, names[0]), [expanded.palette_version]: catalog(expanded, names[1]) };
const output = `// Generated by scripts/sync_color_catalog.mjs from reviewed Python catalog evidence.\nexport type LegoColorCatalog = { version: string; codes: readonly number[]; parts: Readonly<Record<string, readonly number[]>>; evidenceSha256: readonly string[] };\nexport const LEGO_COLOR_CATALOGS: Readonly<Record<string, LegoColorCatalog>> = ${JSON.stringify(catalogs, null, 2)};\nexport const LEGO_COLOR_CATALOG = LEGO_COLOR_CATALOGS["${expanded.palette_version}"];\n`;
const destination = new URL("site/lib/lego-color-catalog.ts", root);
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== output) throw Error("The Site color catalog differs from the converter's reviewed evidence. Run scripts/sync_color_catalog.mjs.");
  console.log("Site and converter color evidence match.");
} else { writeFileSync(destination, output); console.log("Generated Site manufactured part/color catalog."); }
