import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
const root = new URL("../",import.meta.url);
const sourceNames=["source-color-evidence.json","vehicle-color-evidence.json"];
const sources=sourceNames.map(name=>readFileSync(new URL(`lego_builder/data/${name}`,root),"utf8"));
const [source,vehicle]=sources.map(JSON.parse);
const codes=source.color_mappings.map(item=>item.ldraw_color).sort((a,b)=>a-b);
const parts={};
for(const item of [...source.lot_evidence,...vehicle.lot_evidence]) {
  if(item.status!=="verified"||!codes.includes(item.ldraw_color))continue;
  (parts[item.part_id]??=new Set()).add(item.ldraw_color);
}
const catalog={version:source.palette_version,codes,parts:Object.fromEntries(Object.entries(parts).sort(([a],[b])=>a.localeCompare(b)).map(([part,colors])=>[part,[...colors].sort((a,b)=>a-b)])),evidenceSha256:sources.map(value=>createHash("sha256").update(value).digest("hex"))};
const output=`// Generated by scripts/sync_color_catalog.mjs from reviewed Python catalog evidence.\nexport const LEGO_COLOR_CATALOG: { version: string; codes: number[]; parts: Record<string, number[]>; evidenceSha256: string[] } = ${JSON.stringify(catalog,null,2)};\n`;
const destination=new URL("site/lib/lego-color-catalog.ts",root);
if(process.argv.includes("--check")) {
  if(readFileSync(destination,"utf8")!==output)throw Error("The Site color catalog differs from the converter's reviewed evidence. Run scripts/sync_color_catalog.mjs.");
  console.log("Site and converter color evidence match.");
} else {writeFileSync(destination,output);console.log("Generated Site manufactured part/color catalog.");}
