import test from "node:test";
import assert from "node:assert/strict";
import { createGeometryGlb, FalTrellisClient, MeshyImageTo3DClient, ReconstructionError, ReconstructionProviderError, validateGlbAndExportObj, validateImageInput } from "../src/index.ts";

function glb(json: Record<string, unknown>, binary: Uint8Array) {
  const encoder = new TextEncoder(); let j = encoder.encode(JSON.stringify(json)); j = new Uint8Array([...j, ...Array((4 - j.length % 4) % 4).fill(0x20)]); const b = new Uint8Array([...binary, ...Array((4-binary.length%4)%4).fill(0)]);
  const out = new Uint8Array(12 + 8 + j.length + 8 + b.length), d = new DataView(out.buffer); d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,out.length,true);d.setUint32(12,j.length,true);d.setUint32(16,0x4e4f534a,true);out.set(j,20);d.setUint32(20+j.length,b.length,true);d.setUint32(24+j.length,0x004e4942,true);out.set(b,28+j.length);return out;
}
function triangle(transform?: Record<string, unknown>, badIndex=false) { const b=new Uint8Array(42), d=new DataView(b.buffer); [[0,0,0],[1,0,0],[0,1,0]].forEach((p,i)=>p.forEach((v,k)=>d.setFloat32(i*12+k*4,v,true)));d.setUint16(36,0,true);d.setUint16(38,1,true);d.setUint16(40,badIndex?3:2,true); return glb({asset:{version:"2.0"},buffers:[{byteLength:42}],bufferViews:[{byteOffset:0,byteLength:36},{byteOffset:36,byteLength:6}],accessors:[{bufferView:0,componentType:5126,count:3,type:"VEC3"},{bufferView:1,componentType:5123,count:3,type:"SCALAR"}],meshes:[{primitives:[{attributes:{POSITION:0},indices:1}]}],nodes:[{mesh:0,...transform}],scenes:[{nodes:[0]}],scene:0},b); }

test("validates image signatures and dimensions", () => { const png=new Uint8Array(24);png.set([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,3]);assert.deepEqual(validateImageInput(png),{kind:"png",width:2,height:3,bytes:24});assert.throws(()=>validateImageInput(new Uint8Array([1,2,3])),ReconstructionError); });
test("bakes transforms and derives OBJ plus neutral-viewer geometry from GLB triangles", () => { const mesh=validateGlbAndExportObj(triangle({matrix:[2,0,0,0,0,2,0,0,0,0,2,0,3,4,5,1]}));assert.equal(mesh.stats.vertexCount,3);assert.equal(mesh.stats.triangleCount,1);assert.deepEqual(mesh.stats.bounds.min,[3,4,5]);assert.deepEqual([...mesh.geometry.positions],[3,4,5,5,4,5,3,6,5]);assert.deepEqual([...mesh.geometry.indices],[0,1,2]);assert.match(mesh.obj,/v 3 4 5/);assert.match(mesh.obj,/v 5 4 5/);assert.match(mesh.obj,/f 1 2 3/);assert.equal(mesh.manifest.converterEligibility,"unchecked"); });
test("rejects invalid indexes, ranges, and unsupported resources", () => { assert.throws(()=>validateGlbAndExportObj(triangle({},true)),/Index exceeds/);const raw=triangle();const jsonLength=new DataView(raw.buffer).getUint32(12,true);const j=JSON.parse(new TextDecoder().decode(raw.slice(20,20+jsonLength)).trim());j.extensionsUsed=["KHR_draco_mesh_compression"];assert.throws(()=>validateGlbAndExportObj(glb(j,raw.slice(28+jsonLength))),/unsupported resources/);delete j.extensionsUsed;j.bufferViews[0].byteLength=12;assert.throws(()=>validateGlbAndExportObj(glb(j,raw.slice(28+jsonLength))),/Accessor exceeds/); });
test("Meshy adapter resolves statuses, deletes empty 200 response, and maps errors", async () => { let body="";const client=new MeshyImageTo3DClient({apiKey:"secret",fetch:async (_input,init)=>{body=String(init?.body);return init?.method==="DELETE"?new Response(null,{status:200}):new Response(JSON.stringify({result:"task-1"}),{status:201});}});const task=await client.create("data:image/png;base64,AA==");assert.equal(task.id,"task-1");assert.equal(task.status,"PENDING");assert.equal(JSON.parse(body).target_polycount,4000);await client.cancel("task-1");const failing=new MeshyImageTo3DClient({apiKey:"x",fetch:async()=>new Response(JSON.stringify({message:"bad\nrequest"}),{status:429})});await assert.rejects(()=>failing.get("x"),(e:unknown)=>e instanceof ReconstructionProviderError&&e.retryable&&e.message==="bad request"); });
test("creates a self-contained neutral GLB and maps fal queue results", async () => { const original=validateGlbAndExportObj(triangle());assert.deepEqual(validateGlbAndExportObj(createGeometryGlb(original.geometry)).geometry.indices,original.geometry.indices);let calls=0;const client=new FalTrellisClient({apiKey:"x",fetch:async()=>new Response(JSON.stringify(++calls===1?{request_id:"r"}:calls===2?{status:"COMPLETED"}:{model_mesh:{url:"https://signed.example/model.glb"}}))});assert.equal((await client.create("data:image/png;base64,x")).id,"r");assert.equal((await client.get("r")).modelUrl,"https://signed.example/model.glb");});
test("accepts embedded material metadata and rejects external image resources", () => { const raw=triangle(), len=new DataView(raw.buffer).getUint32(12,true), json=JSON.parse(new TextDecoder().decode(raw.slice(20,20+len)).trim());json.extensionsUsed=["KHR_materials_unlit"];json.bufferViews.push({byteOffset:0,byteLength:0});json.images=[{bufferView:2,mimeType:"image/png"}];json.textures=[{source:0}];json.materials=[{extensions:{KHR_materials_unlit:{}},pbrMetallicRoughness:{baseColorTexture:{index:0}}}];json.meshes[0].primitives[0].material=0;const mesh=validateGlbAndExportObj(glb(json,raw.slice(28+len)));assert.deepEqual(validateGlbAndExportObj(createGeometryGlb(mesh.geometry)).geometry.positions,mesh.geometry.positions);json.images=[{uri:"https://evil.example/a.png"}];assert.throws(()=>validateGlbAndExportObj(glb(json,raw.slice(28+len))),/embedded/); });
test("provider errors redact URL tokens", async () => { const client=new FalTrellisClient({apiKey:"api-key-never-returned",fetch:async()=>new Response(JSON.stringify({message:"fetch https://assets.example/x?token=private"}),{status:500})});await assert.rejects(()=>client.create("data:image/png;base64,x"),(e:unknown)=>e instanceof ReconstructionProviderError&&!e.message.includes("private")&&!e.message.includes("assets.example")); });
test("neutral GLB writes POSITION bounds", () => { const mesh=validateGlbAndExportObj(triangle());const output=createGeometryGlb(mesh.geometry),n=new DataView(output.buffer).getUint32(12,true),json=JSON.parse(new TextDecoder().decode(output.slice(20,20+n)).trim());assert.deepEqual(json.accessors[0].min,[0,0,0]);assert.deepEqual(json.accessors[0].max,[1,1,0]); });
