import { ReconstructionError } from "./errors.ts";

export interface GlbLimits { maxBytes?: number; }
const DEFAULT_LIMITS = { maxBytes: 16 * 1024 * 1024, maxVertices: 25_000, maxTriangles: 50_000 };
const MAX_VERTICES = DEFAULT_LIMITS.maxVertices, MAX_TRIANGLES = DEFAULT_LIMITS.maxTriangles;
type Json = Record<string, any>;
export interface MeshStats { vertexCount: number; triangleCount: number; bounds: { min: [number, number, number]; max: [number, number, number] }; }
export interface PreparedMesh { obj: string; geometry: { positions: Float32Array; indices: Uint32Array }; stats: MeshStats; manifest: { version: 1; format: "obj"; sourceFormat: "glb"; transformsBaked: true; axes: "provider-native"; physicalScale: "unknown"; converterEligibility: "unchecked"; validation: "strict-glb-v1"; stats: MeshStats; }; }
function fail(message: string): never { throw new ReconstructionError(message, "INVALID_GLB"); }
function object(v: unknown, name: string): Json { if (!v || typeof v !== "object" || Array.isArray(v)) fail(`Invalid ${name}`); return v as Json; }
function array(v: unknown, name: string): any[] { if (!Array.isArray(v)) fail(`Invalid ${name}`); return v; }
function number(v: unknown, name: string): number { if (typeof v !== "number" || !Number.isFinite(v)) fail(`Invalid ${name}`); return v; }
function integer(v: unknown, name: string): number { const n = number(v, name); if (!Number.isInteger(n) || n < 0) fail(`Invalid ${name}`); return n; }
function matrixMultiply(a: number[], b: number[]) { const r = Array(16).fill(0); for (let c=0;c<4;c++) for(let row=0;row<4;row++) for(let k=0;k<4;k++) r[c*4+row] += a[k*4+row]*b[c*4+k]; return r; }
function nodeMatrix(node: Json): number[] {
  if (node.matrix !== undefined) { const m=array(node.matrix,"node matrix"); if(m.length!==16) fail("Invalid node matrix"); return m.map((x,i)=>number(x,`node matrix ${i}`)); }
  const t=node.translation===undefined?[0,0,0]:array(node.translation,"translation").map((x,i)=>number(x,`translation ${i}`));
  const s=node.scale===undefined?[1,1,1]:array(node.scale,"scale").map((x,i)=>number(x,`scale ${i}`));
  const q=node.rotation===undefined?[0,0,0,1]:array(node.rotation,"rotation").map((x,i)=>number(x,`rotation ${i}`));
  if(t.length!==3||s.length!==3||q.length!==4) fail("Invalid node transform");
  const [x,y,z,w]=q, xx=x*x, yy=y*y, zz=z*z, xy=x*y, xz=x*z, yz=y*z, wx=w*x, wy=w*y, wz=w*z;
  return [(1-2*(yy+zz))*s[0],(2*(xy+wz))*s[0],(2*(xz-wy))*s[0],0,(2*(xy-wz))*s[1],(1-2*(xx+zz))*s[1],(2*(yz+wx))*s[1],0,(2*(xz+wy))*s[2],(2*(yz-wx))*s[2],(1-2*(xx+yy))*s[2],0,t[0],t[1],t[2],1];
}
function transform(m:number[], x:number,y:number,z:number): [number,number,number] { const w=m[3]*x+m[7]*y+m[11]*z+m[15]; if(!Number.isFinite(w)||w===0) fail("Invalid transformed vertex"); const p:[number,number,number]=[(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w]; if(!p.every(Number.isFinite)) fail("Invalid transformed vertex"); return p; }
function determinant3(m:number[]) { return m[0]*(m[5]*m[10]-m[6]*m[9])-m[4]*(m[1]*m[10]-m[2]*m[9])+m[8]*(m[1]*m[6]-m[2]*m[5]); }

/** Creates a compact, self-contained GLB from already validated baked geometry. */
export function createGeometryGlb(geometry: { positions: Float32Array; indices: Uint32Array }): Uint8Array {
  if(!geometry.positions.length||geometry.positions.length%3||geometry.indices.length%3||geometry.positions.some(x=>!Number.isFinite(x))) fail("Invalid geometry"); const vertices=geometry.positions.length/3;if(vertices>MAX_VERTICES||geometry.indices.length/3>MAX_TRIANGLES||geometry.indices.some(x=>x>=vertices))fail("Mesh resource limit exceeded");
  const bin=new Uint8Array(geometry.positions.byteLength+geometry.indices.byteLength);bin.set(new Uint8Array(geometry.positions.buffer,geometry.positions.byteOffset,geometry.positions.byteLength));bin.set(new Uint8Array(geometry.indices.buffer,geometry.indices.byteOffset,geometry.indices.byteLength),geometry.positions.byteLength);
  const min:[number,number,number]=[Infinity,Infinity,Infinity],max:[number,number,number]=[-Infinity,-Infinity,-Infinity];for(let i=0;i<geometry.positions.length;i+=3)for(let k=0;k<3;k++){min[k]=Math.min(min[k],geometry.positions[i+k]);max[k]=Math.max(max[k],geometry.positions[i+k]);}
  let json=new TextEncoder().encode(JSON.stringify({asset:{version:"2.0",generator:"LEGO Builder geometry export"},buffers:[{byteLength:bin.length}],bufferViews:[{buffer:0,byteOffset:0,byteLength:geometry.positions.byteLength},{buffer:0,byteOffset:geometry.positions.byteLength,byteLength:geometry.indices.byteLength}],accessors:[{bufferView:0,componentType:5126,count:vertices,type:"VEC3",min,max},{bufferView:1,componentType:5125,count:geometry.indices.length,type:"SCALAR"}],meshes:[{primitives:[{attributes:{POSITION:0},indices:1,mode:4}]}],nodes:[{mesh:0}],scenes:[{nodes:[0]}],scene:0}));json=new Uint8Array([...json,...Array((4-json.length%4)%4).fill(0x20)]);const out=new Uint8Array(12+8+json.length+8+bin.length),d=new DataView(out.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,out.length,true);d.setUint32(12,json.length,true);d.setUint32(16,0x4e4f534a,true);out.set(json,20);d.setUint32(20+json.length,bin.length,true);d.setUint32(24+json.length,0x004e4942,true);out.set(bin,28+json.length);return out;
}

/** Strict, self-contained GLB subset: position-only triangle primitives, float32 positions and uint8/16/32 indices. */
export function validateGlbAndExportObj(bytes: Uint8Array, suppliedLimits: GlbLimits = {}): PreparedMesh {
  const limits = { ...DEFAULT_LIMITS, ...suppliedLimits };
  if(bytes.byteLength<20||bytes.byteLength>limits.maxBytes) fail("GLB size is unsupported"); const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
  if(view.getUint32(0,true)!==0x46546c67||view.getUint32(4,true)!==2||view.getUint32(8,true)!==bytes.byteLength) fail("Invalid GLB header");
  let off=12, json:Json|undefined, bin:Uint8Array|undefined;
  while(off+8<=bytes.byteLength){ const len=view.getUint32(off,true), typ=view.getUint32(off+4,true); off+=8; if(len%4||off+len>bytes.byteLength) fail("Invalid GLB chunk"); const chunk=bytes.slice(off,off+len); off+=len; if(typ===0x4e4f534a){if(len>1024*1024)fail("GLB metadata limit exceeded");if(json)fail("Multiple JSON chunks");try{json=object(JSON.parse(new TextDecoder().decode(chunk).trim()),"GLB JSON");}catch{fail("Invalid GLB JSON");}} else if(typ===0x004e4942){if(bin)fail("Multiple binary chunks");bin=chunk;} else fail("Unsupported GLB chunk"); }
  if(off!==bytes.byteLength||!json||!bin) fail("GLB must contain JSON and binary chunks"); const extensions=[...array(json.extensionsUsed??[],"extensionsUsed"),...array(json.extensionsRequired??[],"extensionsRequired")]; if(!extensions.every(x=>x==="KHR_materials_unlit")||json.animations||json.skins) fail("GLB uses unsupported resources");
  if(!json.asset||json.asset.version!=="2.0") fail("Unsupported glTF version"); const buffers=array(json.buffers,"buffers"); if(buffers.length!==1||object(buffers[0],"buffer").uri!==undefined||integer(buffers[0].byteLength,"buffer byteLength")>bin.byteLength) fail("GLB must have one embedded buffer");
  const bufferViews=array(json.bufferViews??[],"bufferViews"), accessors=array(json.accessors??[],"accessors"), meshes=array(json.meshes??[],"meshes"), nodes=array(json.nodes??[],"nodes");
  if(nodes.length>1024)fail("Node graph exceeds resource limit");
  for(const candidate of accessors){const a=object(candidate,"accessor");if(integer(a.count,"accessor count")>MAX_TRIANGLES*3)fail("Accessor exceeds resource limit");}
  for(const image of array(json.images??[],"images")){const img=object(image,"image");if(img.uri!==undefined||img.bufferView===undefined)fail("GLB image must be embedded");const bv=object(bufferViews[integer(img.bufferView,"image bufferView")],"image bufferView");if(integer(bv.byteOffset??0,"image offset")+integer(bv.byteLength,"image length")>bin.byteLength)fail("Image exceeds binary buffer");}
  const access=(id:unknown)=>{const a=object(accessors[integer(id,"accessor index")],"accessor"); if(a.sparse||a.bufferView===undefined||a.normalized)fail("Sparse, normalized, or detached accessors are unsupported");const bv=object(bufferViews[integer(a.bufferView,"bufferView index")],"bufferView");if(integer(bv.buffer??0,"bufferView buffer")!==0)fail("Buffer view references an unsupported buffer");const viewStart=integer(bv.byteOffset??0,"bufferView offset"), viewLength=integer(bv.byteLength,"bufferView length"), start=viewStart+integer(a.byteOffset??0,"accessor offset"), count=integer(a.count,"accessor count"), component=integer(a.componentType,"component type"), components=a.type==="VEC3"?3:a.type==="SCALAR"?1:0, size=component===5126?4:component===5121?1:component===5123?2:component===5125?4:0, stride=integer(bv.byteStride??size*components,"accessor stride"), end=start+((count?count-1:0)*stride+size*components); if(!components||!size||stride<size*components||viewStart+viewLength>bin.byteLength||end>viewStart+viewLength)fail("Accessor exceeds binary buffer");return {start,count,component,components,size,stride,a};};
  const lines:string[]=["# LEGO Builder prepared geometry-only OBJ", "# source: validated GLB; physical scale unknown"], positions:number[]=[], outputIndices:number[]=[], min:[number,number,number]=[Infinity,Infinity,Infinity],max:[number,number,number]=[-Infinity,-Infinity,-Infinity]; let vertices=0,triangles=0,visitCount=0;
  const visit=(nodeId:number,parent:number[],stack:Set<number>)=>{if(++visitCount>4096||stack.size>64)fail("Node graph exceeds resource limit");if(stack.has(nodeId))fail("Cyclic node graph");const node=object(nodes[nodeId],"node");if(node.skin!==undefined||node.weights!==undefined)fail("Unsupported skinning or morph weights");const world=matrixMultiply(parent,nodeMatrix(node)); if(node.mesh!==undefined){const mesh=object(meshes[integer(node.mesh,"mesh index")],"mesh");if(mesh.weights||mesh.extensions||!Array.isArray(mesh.primitives))fail("Unsupported mesh");for(const primitive of mesh.primitives){const p=object(primitive,"primitive");if((p.mode??4)!==4||p.targets||p.extensions)fail("Only triangle primitives without morph targets are supported");const position=access(object(p.attributes,"primitive attributes").POSITION);if(position.component!==5126||position.components!==3||position.stride<12||position.count===0)fail("Positions must be nonempty float32 VEC3");let indices:number[]=[];if(p.indices===undefined){if(position.count%3)fail("Unindexed positions must form triangles");indices=Array.from({length:position.count},(_,i)=>i);}else{const idx=access(p.indices);if(idx.components!==1||![5121,5123,5125].includes(idx.component)||idx.count%3)fail("Indices must be unsigned triangle indices");for(let i=0;i<idx.count;i++){const at=idx.start+i*idx.stride;indices.push(idx.component===5121?bin![at]:idx.component===5123?new DataView(bin!.buffer,bin!.byteOffset+at,2).getUint16(0,true):new DataView(bin!.buffer,bin!.byteOffset+at,4).getUint32(0,true));}}if(indices.some(i=>i>=position.count))fail("Index exceeds position count");if(vertices+position.count>MAX_VERTICES||triangles+indices.length/3>MAX_TRIANGLES)fail("Mesh resource limit exceeded");const base=vertices, reflected=determinant3(world);if(!Number.isFinite(reflected)||Math.abs(reflected)<1e-12)fail("Invalid node transform");for(let i=0;i<position.count;i++){const d=new DataView(bin!.buffer,bin!.byteOffset+position.start+i*position.stride,12), pt=transform(world,d.getFloat32(0,true),d.getFloat32(4,true),d.getFloat32(8,true));if(!pt.every(v=>Number.isFinite(Math.fround(v))))fail("Transformed vertex exceeds float32 range");positions.push(...pt);for(let k=0;k<3;k++){min[k]=Math.min(min[k],pt[k]);max[k]=Math.max(max[k],pt[k]);}lines.push(`v ${pt[0]} ${pt[1]} ${pt[2]}`);}for(let i=0;i<indices.length;i+=3){const a=base+indices[i],b=base+indices[i+1],c=base+indices[i+2];outputIndices.push(a,reflected<0?c:b,reflected<0?b:c);lines.push(`f ${a+1} ${(reflected<0?c:b)+1} ${(reflected<0?b:c)+1}`);}vertices+=position.count;triangles+=indices.length/3;}}
    for(const child of array(node.children??[],"node children"))visit(integer(child,"node child"),world,new Set([...stack,nodeId])); };
  const sceneIndex=integer(json.scene??0,"scene index"), scenes=array(json.scenes??[],"scenes"); if(!scenes.length)fail("GLB has no scene"); for(const root of array(object(scenes[sceneIndex],"scene").nodes??[],"scene nodes")) visit(integer(root,"scene node"),[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],new Set());
  if(!vertices||!triangles)fail("GLB contains no triangles"); const stats:MeshStats={vertexCount:vertices,triangleCount:triangles,bounds:{min,max}}; return {obj:lines.join("\n")+"\n",geometry:{positions:new Float32Array(positions),indices:new Uint32Array(outputIndices)},stats,manifest:{version:1,format:"obj",sourceFormat:"glb",transformsBaked:true,axes:"provider-native",physicalScale:"unknown",converterEligibility:"unchecked",validation:"strict-glb-v1",stats}};
}
